import pandas as pd
import os
import glob

configfile: "config/config.yaml"
include: "rules/common.smk"
include: "rules/other.smk"
include: "rules/leafcutterMD_v2.smk"



localrules: all

rule all:
    input:
        'resources/All_perind_rail_id_tissue_type_lookup.tsv',
        expand('results/leafcutterMD/{data_source}/{tissue}/LeafcutterMD.done', 
                data_source = ['GTEx'], tissue = ['Bladder', 'Kidney', 'Muscle'])


