configfile: "config/config.yaml"
include: "rules/common.smk"
include: "rules/other.smk"
include: "rules/leafcutter.smk"


# localrules: all

# rule all:
    # input:
        # expand('results/ComputeMatrix/{FeatureType}/heatmap.pdf', FeatureType=FEATURE_TYPES2)
